export interface DetailedLesson {
  id: number;
  title: string;
  intro: string;
  explanation: string;
  example: string;
  activity: string;
  question: string;
  choices: [string, string, string];
  answer: string;
}

export interface TopicCurriculum {
  subject: string;
  level: string;
  eyebrow: string;
  lessons: DetailedLesson[];
}

export const TOPIC_CURRICULA: Record<string, TopicCurriculum> = {
  Fractions: {
    subject: "Maths",
    level: "Grade 7",
    eyebrow: "Parts of a whole",
    lessons: [
      {
        id: 0,
        title: "1. Understanding Fractions",
        intro: "Fractions describe equal parts of a whole and help us compare quantities clearly.",
        explanation: "A fraction has a numerator, which tells us how many parts we have, and a denominator, which tells us how many equal parts make up the whole.",
        example: "3/4 = 3 parts out of 4 total equal parts",
        activity: "Shade 3 of 4 equal parts on a grid, then notice that 1 part remains unshaded (1/4).",
        question: "Which number is the denominator in 3/4?",
        choices: ["3", "4", "7"],
        answer: "4",
      },
      {
        id: 1,
        title: "2. Fractions on a Number Line",
        intro: "Number lines help us visualize where fractions lie between whole numbers.",
        explanation: "Divide the interval between 0 and 1 into equal segments based on the denominator, then count segments to find the numerator position.",
        example: "1/2 is halfway between 0 and 1 on a number line.",
        activity: "Place 1/4, 2/4, and 3/4 on a number line between 0 and 1.",
        question: "Where does 2/4 lie on a number line between 0 and 1?",
        choices: ["At 0.25", "Exactly at the midpoint (0.5)", "At 0.75"],
        answer: "Exactly at the midpoint (0.5)",
      },
      {
        id: 2,
        title: "3. Comparing Fractions",
        intro: "Compare fractions by finding a common denominator or using benchmarks like 1/2.",
        explanation: "When denominators are equal, the fraction with the larger numerator is greater. When numerators are equal, smaller denominators mean bigger parts.",
        example: "3/5 is greater than 2/5 because 3 > 2.",
        activity: "Compare 2/3 and 3/4 by converting both to twelfths: 8/12 vs 9/12.",
        question: "Which fraction is larger: 3/4 or 2/4?",
        choices: ["3/4", "2/4", "They are equal"],
        answer: "3/4",
      },
      {
        id: 3,
        title: "4. Equivalent Fractions",
        intro: "Equivalent fractions look different but represent the exact same value.",
        explanation: "Multiply or divide both the numerator and denominator by the same non-zero number to get an equivalent fraction.",
        example: "1/2 = 2/4 = 3/6 = 4/8",
        activity: "Multiply both parts of 1/2 by 2, 3, and 4 to generate three equivalent fractions.",
        question: "Which fraction is equivalent to 1/2?",
        choices: ["2/4", "1/3", "3/5"],
        answer: "2/4",
      },
      {
        id: 4,
        title: "5. Simplifying Fractions",
        intro: "Simplifying means dividing top and bottom numbers by their greatest common factor (GCF).",
        explanation: "A fraction is in simplest form when the only common factor between its numerator and denominator is 1.",
        example: "6/8 simplified by dividing by 2 yields 3/4.",
        activity: "Simplify 4/12 by finding GCF=4 to get 1/3.",
        question: "What is 4/8 in simplest form?",
        choices: ["1/2", "2/4", "1/4"],
        answer: "1/2",
      },
      {
        id: 5,
        title: "6. Adding Fractions with Like Denominators",
        intro: "Add the numerators together while keeping the denominator the same.",
        explanation: "Since the size of the parts is identical, add the total number of parts together.",
        example: "1/5 + 2/5 = 3/5",
        activity: "Combine 2/7 and 3/7 to make 5/7 of a pie.",
        question: "What is 2/7 + 3/7?",
        choices: ["5/14", "5/7", "6/7"],
        answer: "5/7",
      },
      {
        id: 6,
        title: "7. Subtracting Fractions with Like Denominators",
        intro: "Subtract the numerators while maintaining the common denominator.",
        explanation: "When subtracting parts of the same size, subtract the top numbers and keep the bottom number unchanged.",
        example: "5/8 - 2/8 = 3/8",
        activity: "Start with 7/10 of a chocolate bar and eat 3/10. Calculate what remains.",
        question: "What is 5/8 - 2/8?",
        choices: ["3/8", "3/0", "7/8"],
        answer: "3/8",
      },
      {
        id: 7,
        title: "8. Mixed Numbers & Improper Fractions",
        intro: "Convert between whole numbers with fractions and fractions larger than 1.",
        explanation: "An improper fraction has a numerator greater than or equal to its denominator. A mixed number combines a whole number and a proper fraction.",
        example: "7/4 = 1 3/4",
        activity: "Convert 2 1/2 into an improper fraction: (2 × 2 + 1) / 2 = 5/2.",
        question: "What is 7/4 written as a mixed number?",
        choices: ["1 3/4", "1 1/4", "2 1/4"],
        answer: "1 3/4",
      },
      {
        id: 8,
        title: "9. Adding & Subtracting Unlike Fractions",
        intro: "Find a common denominator before adding or subtracting fractions.",
        explanation: "Convert both fractions to equivalent fractions with the Least Common Denominator (LCD), then add or subtract numerators.",
        example: "1/2 + 1/3 = 3/6 + 2/6 = 5/6",
        activity: "Add 1/4 + 1/2 by changing 1/2 to 2/4.",
        question: "What is 1/2 + 1/4?",
        choices: ["3/4", "2/6", "1/6"],
        answer: "3/4",
      },
      {
        id: 9,
        title: "10. Multiplying Fractions",
        intro: "Multiply numerators together and denominators together directly.",
        explanation: "To multiply two fractions, multiply top × top and bottom × bottom, then simplify the result if needed.",
        example: "2/3 × 3/4 = 6/12 = 1/2",
        activity: "Calculate 1/2 of 1/4 of a pizza = 1/8.",
        question: "What is 1/2 × 3/4?",
        choices: ["3/8", "4/6", "3/6"],
        answer: "3/8",
      },
      {
        id: 10,
        title: "11. Dividing Fractions",
        intro: "Multiply by the reciprocal (flip the second fraction and multiply).",
        explanation: "Keep the first fraction, change division to multiplication, and flip the second fraction upside down.",
        example: "1/2 ÷ 1/4 = 1/2 × 4/1 = 4/2 = 2",
        activity: "Divide 3/4 by 1/2 by multiplying 3/4 × 2/1 = 6/4 = 1 1/2.",
        question: "What is 1/2 ÷ 1/2?",
        choices: ["1", "1/4", "2"],
        answer: "1",
      },
      {
        id: 11,
        title: "12. Real-World Fraction Problems",
        intro: "Apply fraction concepts to recipe scaling, measurements, and word problems.",
        explanation: "Identify the whole quantity, choose the appropriate fraction operation, and solve step-by-step.",
        example: "A recipe needs 3/4 cup sugar. If you make half a batch, use 3/4 × 1/2 = 3/8 cup.",
        activity: "Calculate how many 1/4 cup servings are in 3 cups of flour.",
        question: "If a recipe calls for 2/3 cup of milk and you double it, how much milk do you need?",
        choices: ["4/3 cups (1 1/3)", "4/6 cups", "2/6 cups"],
        answer: "4/3 cups (1 1/3)",
      },
    ],
  },

  "Linear equations": {
    subject: "Maths",
    level: "Grade 7",
    eyebrow: "Balance methods",
    lessons: [
      {
        id: 0,
        title: "1. Introduction to Variables",
        intro: "A variable is a letter representing an unknown number in an expression or equation.",
        explanation: "Variables like x, y, or n act as placeholders for values we want to solve for.",
        example: "In x + 5 = 12, x is the variable representing 7.",
        activity: "Substitute x = 4 into 3x + 2 to get 3(4) + 2 = 14.",
        question: "In the expression 5y - 3, what is y called?",
        choices: ["Variable", "Constant", "Coefficient"],
        answer: "Variable",
      },
      {
        id: 1,
        title: "2. One-Step Addition & Subtraction Equations",
        intro: "Use inverse operations to isolate the variable in single-step equations.",
        explanation: "To undo addition, subtract from both sides. To undo subtraction, add to both sides.",
        example: "x + 7 = 15 → x = 15 - 7 → x = 8",
        activity: "Solve y - 4 = 11 by adding 4 to both sides.",
        question: "Solve x + 5 = 12.",
        choices: ["7", "17", "6"],
        answer: "7",
      },
      {
        id: 2,
        title: "3. One-Step Multiplication & Division Equations",
        intro: "Undo multiplication with division, and division with multiplication.",
        explanation: "Keep the balance scale equal by applying the exact inverse operation to both sides.",
        example: "3x = 21 → x = 21 / 3 → x = 7",
        activity: "Solve m / 4 = 5 by multiplying both sides by 4.",
        question: "Solve 4x = 24.",
        choices: ["6", "20", "28"],
        answer: "6",
      },
      {
        id: 3,
        title: "4. Two-Step Linear Equations",
        intro: "Solve for an unknown by keeping both sides of the equation balanced.",
        explanation: "Whatever operation you apply to one side of an equation, apply the same operation to the other side so equality stays true.",
        example: "2x + 3 = 11 → 2x = 8 → x = 4",
        activity: "Subtract 3 from both sides, then divide both sides by 2.",
        question: "What is x in 2x + 3 = 11?",
        choices: ["3", "4", "7"],
        answer: "4",
      },
      {
        id: 4,
        title: "5. Equations with Variables on Both Sides",
        intro: "Collect variable terms on one side and constant terms on the other.",
        explanation: "Subtract the smaller variable term from both sides, then isolate the variable.",
        example: "5x + 2 = 3x + 10 → 2x = 8 → x = 4",
        activity: "Solve 4x - 5 = 2x + 7 step by step.",
        question: "Solve 3x = x + 8.",
        choices: ["4", "2", "8"],
        answer: "4",
      },
      {
        id: 5,
        title: "6. Simplifying Before Solving",
        intro: "Combine like terms on each side of the equals sign before solving.",
        explanation: "Group numbers together and variables together on each side before using balance steps.",
        example: "2x + 3x + 4 = 19 → 5x + 4 = 19 → 5x = 15 → x = 3",
        activity: "Simplify 7x - 2x + 1 = 16 to 5x + 1 = 16.",
        question: "What is x if 2x + 3x = 25?",
        choices: ["5", "10", "25"],
        answer: "5",
      },
      {
        id: 6,
        title: "7. Combining Like Terms in Equations",
        intro: "Identify terms with matching variable parts and combine their coefficients.",
        explanation: "Terms with the exact same variables raised to the same power are like terms.",
        example: "4a + 2b - a + 3b = 3a + 5b",
        activity: "Combine terms in 6y + 4 - 2y + 8.",
        question: "Simplify 4x + 3x - 2x.",
        choices: ["5x", "7x", "9x"],
        answer: "5x",
      },
      {
        id: 7,
        title: "8. Equations with Parentheses",
        intro: "Use the distributive property to expand parentheses before isolating x.",
        explanation: "Multiply the term outside the parentheses by every term inside.",
        example: "2(x + 4) = 14 → 2x + 8 = 14 → 2x = 6 → x = 3",
        activity: "Expand and solve 3(y - 2) = 15.",
        question: "Solve 2(x + 3) = 10.",
        choices: ["2", "4", "5"],
        answer: "2",
      },
      {
        id: 8,
        title: "9. Solving Word Problems with Linear Equations",
        intro: "Translate written scenarios into mathematical equations and solve.",
        explanation: "Define the unknown variable, write down the relationship as an equation, and solve.",
        example: "Sam has \$5 more than twice Alex's money. If Sam has \$25, twice Alex's money + 5 = 25.",
        activity: "Write an equation for: 'A number doubled plus 6 equals 20'.",
        question: "If 2n + 6 = 20, what is n?",
        choices: ["7", "14", "10"],
        answer: "7",
      },
      {
        id: 9,
        title: "10. Multi-Step Linear Equations",
        intro: "Combine expansion, combining like terms, and isolating variables.",
        explanation: "Follow PEMDAS for expanding, simplify both sides, collect variables, and isolate.",
        example: "3(x + 1) + 2x = 18 → 5x + 3 = 18 → x = 3",
        activity: "Solve 4(x - 1) - 2 = 14.",
        question: "Solve 3x + 2(x + 1) = 12.",
        choices: ["2", "3", "4"],
        answer: "2",
      },
      {
        id: 10,
        title: "11. Equations with Fractions & Decimals",
        intro: "Clear fractions by multiplying all terms by the common denominator.",
        explanation: "Multiplying every term in an equation by the LCD eliminates fractions for simpler solving.",
        example: "x/2 + 1/3 = 5/6 → 3x + 2 = 5 → 3x = 3 → x = 1",
        activity: "Multiply 0.5x + 1.2 = 3.2 by 10 to get 5x + 12 = 32.",
        question: "Solve x/3 + 2 = 5.",
        choices: ["9", "3", "15"],
        answer: "9",
      },
      {
        id: 11,
        title: "12. Real-World Applications & Systems Intro",
        intro: "Apply equations to calculate rates, distances, costs, and multi-variable setups.",
        explanation: "Linear equations model real-life situations where change occurs at a constant rate.",
        example: "Cost = \$10 flat fee + \$2 per mile → C = 10 + 2m.",
        activity: "Calculate total cost for a 15-mile ride using C = 10 + 2(15).",
        question: "If C = 10 + 2m and C = 40, how many miles m were traveled?",
        choices: ["15", "20", "25"],
        answer: "15",
      },
    ],
  },

  Geometry: {
    subject: "Maths",
    level: "Grade 7",
    eyebrow: "Angles and triangles",
    lessons: [
      {
        id: 0,
        title: "1. Point, Line, and Angle Basics",
        intro: "Geometry begins with fundamental elements: points, lines, rays, and angles.",
        explanation: "An angle is formed when two rays share a common endpoint called a vertex.",
        example: "An angle measuring 90° forms a sharp square corner.",
        activity: "Identify acute (<90°), right (90°), and obtuse (>90°) angles around your classroom.",
        question: "What is an angle measuring less than 90° called?",
        choices: ["Acute angle", "Right angle", "Obtuse angle"],
        answer: "Acute angle",
      },
      {
        id: 1,
        title: "2. Types of Angles & Measuring",
        intro: "Angles are measured in degrees (°) using a protractor.",
        explanation: "Complementary angles sum to 90°; supplementary angles sum to 180°.",
        example: "If angle A is 60°, its supplementary angle B is 120°.",
        activity: "Find the supplementary angle of 70°.",
        question: "What is the supplement of an 80° angle?",
        choices: ["100°", "10°", "90°"],
        answer: "100°",
      },
      {
        id: 2,
        title: "3. Parallel and Perpendicular Lines",
        intro: "Parallel lines never cross; perpendicular lines intersect at 90°.",
        explanation: "When a transversal crosses parallel lines, corresponding and alternate interior angles are equal.",
        example: "Perpendicular lines form four right angles at their intersection point.",
        activity: "Draw two parallel lines intersected by a diagonal line and mark equal angles.",
        question: "What angle do perpendicular lines form?",
        choices: ["90°", "180°", "45°"],
        answer: "90°",
      },
      {
        id: 3,
        title: "4. Triangles & Angle Sum Rule",
        intro: "Geometry helps us describe shapes, space, and the relationships between lines and angles.",
        explanation: "The angles inside every triangle add up to 180°. Use known angles to work out the missing one.",
        example: "60° + 50° + 70° = 180°",
        activity: "Draw a triangle and label two angles (50° and 60°). Calculate the third angle.",
        question: "What is the angle sum of a triangle?",
        choices: ["90°", "180°", "360°"],
        answer: "180°",
      },
      {
        id: 4,
        title: "5. Classifying Triangles",
        intro: "Classify triangles by side lengths (equilateral, isosceles, scalene) or angles.",
        explanation: "Equilateral has 3 equal sides, Isosceles has 2, and Scalene has 0 equal sides.",
        example: "An equilateral triangle has three 60° interior angles.",
        activity: "Identify a triangle with side lengths 5cm, 5cm, and 8cm as isosceles.",
        question: "A triangle with all 3 sides equal is called:",
        choices: ["Equilateral", "Isosceles", "Scalene"],
        answer: "Equilateral",
      },
      {
        id: 5,
        title: "6. Quadrilaterals & Polygons",
        intro: "Four-sided shapes are quadrilaterals; their interior angles always sum to 360°.",
        explanation: "Parallelograms, rectangles, squares, rhombuses, and trapezoids are all quadrilaterals.",
        example: "A square has 4 equal sides and 4 right angles.",
        activity: "Calculate the missing angle in a quadrilateral with angles 90°, 90°, 100°, x.",
        question: "What is the interior angle sum of a quadrilateral?",
        choices: ["360°", "180°", "540°"],
        answer: "360°",
      },
      {
        id: 6,
        title: "7. Perimeter of Plane Figures",
        intro: "Perimeter is the total distance around the outside edge of a 2D shape.",
        explanation: "Add all boundary side lengths together to calculate the perimeter.",
        example: "Perimeter of a 4m by 6m rectangle = 4 + 6 + 4 + 6 = 20m.",
        activity: "Calculate the perimeter of a regular hexagon with side length 5 cm.",
        question: "What is the perimeter of a rectangle with length 8 cm and width 3 cm?",
        choices: ["22 cm", "24 cm", "11 cm"],
        answer: "22 cm",
      },
      {
        id: 7,
        title: "8. Area of Rectangles & Triangles",
        intro: "Area measures the amount of 2D space inside a boundary.",
        explanation: "Rectangle area = base × height. Triangle area = 1/2 × base × height.",
        example: "Triangle with base 10cm and height 4cm has Area = 1/2 × 10 × 4 = 20 cm².",
        activity: "Compare the area of a 6×4 rectangle with a triangle having base 6 and height 4.",
        question: "What is the area of a triangle with base 6 cm and height 4 cm?",
        choices: ["12 cm²", "24 cm²", "10 cm²"],
        answer: "12 cm²",
      },
      {
        id: 8,
        title: "9. Circumference of Circles",
        intro: "Circumference is the distance around a circle: C = 2πr or C = πd.",
        explanation: "Pi (π ≈ 3.14159) is the ratio of a circle's circumference to its diameter.",
        example: "Circle with diameter 10cm has C ≈ 3.14 × 10 = 31.4 cm.",
        activity: "Calculate circumference for a circle of radius 7cm (use π ≈ 22/7).",
        question: "What formula gives the circumference of a circle?",
        choices: ["2πr", "πr²", "1/2 bh"],
        answer: "2πr",
      },
      {
        id: 9,
        title: "10. Area of Circles",
        intro: "Calculate circle area using Area = πr².",
        explanation: "Square the radius first, then multiply by π to determine 2D circular area.",
        example: "Circle with radius 3cm has Area = π × 3² = 9π ≈ 28.26 cm².",
        activity: "Find area of a circle with diameter 8cm (radius = 4cm).",
        question: "If radius r = 5 cm, what is the circle area (using π ≈ 3.14)?",
        choices: ["78.5 cm²", "31.4 cm²", "25 cm²"],
        answer: "78.5 cm²",
      },
      {
        id: 10,
        title: "11. 3D Shapes & Net Diagrams",
        intro: "3D shapes have faces, edges, and vertices; nets unfold 3D objects into 2D plans.",
        explanation: "A cube net consists of 6 connected square faces.",
        example: "A rectangular prism has 6 rectangular faces, 12 edges, and 8 vertices.",
        activity: "Draw the net diagram of a triangular prism.",
        question: "How many faces does a cube have?",
        choices: ["6", "8", "12"],
        answer: "6",
      },
      {
        id: 11,
        title: "12. Volume of Cubes & Rectangular Prisms",
        intro: "Volume measures the 3D space contained inside a solid object: V = l × w × h.",
        explanation: "Volume is expressed in cubic units (cm³, m³). For prisms, Volume = Base Area × Height.",
        example: "Prism with length 5m, width 3m, height 2m has V = 5 × 3 × 2 = 30 m³.",
        activity: "Calculate volume of a cube with side length 4 cm.",
        question: "What is the volume of a box measuring 4cm × 3cm × 2cm?",
        choices: ["24 cm³", "18 cm³", "9 cm³"],
        answer: "24 cm³",
      },
      {
        id: 12,
        title: "13. Surface Area Basics",
        intro: "Surface area is the total area of all 2D faces enclosing a 3D solid.",
        explanation: "Sum the area of every face of the solid.",
        example: "Surface area of a cube with side 3cm = 6 × (3 × 3) = 54 cm².",
        activity: "Calculate surface area of a box measuring 2×3×4 cm.",
        question: "What is the surface area of a cube with side length 2 cm?",
        choices: ["24 cm²", "8 cm²", "16 cm²"],
        answer: "24 cm²",
      },
      {
        id: 13,
        title: "14. Geometric Problem Solving",
        intro: "Combine geometric rules to solve real-world architectural and spatial challenges.",
        explanation: "Use angle rules, perimeter, area, and volume formulas together in multi-step problems.",
        example: "Determine how many tiles of 20×20 cm are needed to cover a 2×3 m floor.",
        activity: "Calculate tile count for a kitchen floor layout.",
        question: "How many 1m² tiles are needed to pave a 5m by 4m patio?",
        choices: ["20", "18", "9"],
        answer: "20",
      },
    ],
  },

  Photosynthesis: {
    subject: "Science",
    level: "Grade 6",
    eyebrow: "Light-dependent reactions",
    lessons: [
      {
        id: 0,
        title: "1. What is Photosynthesis?",
        intro: "Plants use light energy to make the food they need to survive and grow.",
        explanation: "In photosynthesis, leaves use sunlight, water, and carbon dioxide to produce glucose and oxygen inside chloroplasts.",
        example: "Sunlight + water + carbon dioxide → glucose + oxygen",
        activity: "Trace the path from sunlight to glucose in a leaf, then explain why oxygen is released.",
        question: "Which gas do plants take in during photosynthesis?",
        choices: ["Carbon dioxide", "Oxygen", "Nitrogen"],
        answer: "Carbon dioxide",
      },
      {
        id: 1,
        title: "2. Plant Cell Structure & Chloroplasts",
        intro: "Chloroplasts are specialized organelles inside plant cells where photosynthesis occurs.",
        explanation: "Chloroplasts contain green pigment called chlorophyll that absorbs solar light energy.",
        example: "Leaf cells near the upper surface contain high concentrations of chloroplasts.",
        activity: "Examine a plant cell diagram and locate the cell wall, vacuole, and chloroplasts.",
        question: "Which organelle houses chlorophyll?",
        choices: ["Chloroplast", "Nucleus", "Mitochondria"],
        answer: "Chloroplast",
      },
      {
        id: 2,
        title: "3. Role of Sunlight & Solar Energy",
        intro: "Sunlight provides the essential energy required to drive the chemical reactions of photosynthesis.",
        explanation: "Light photons excite electrons in chlorophyll, initiating the conversion of light energy into chemical energy.",
        example: "Plants grown in dark rooms cannot produce glucose and turn yellow.",
        activity: "Observe how leaves turn toward sunlight (phototropism).",
        question: "What form of energy drives photosynthesis?",
        choices: ["Light energy", "Heat energy", "Electrical energy"],
        answer: "Light energy",
      },
      {
        id: 3,
        title: "4. Carbon Dioxide & Stomata",
        intro: "Plants absorb carbon dioxide gas from the air through microscopic leaf pores called stomata.",
        explanation: "Guard cells surround stomata and open or close the pores to balance gas exchange and water loss.",
        example: "Stomata open during the day for CO2 intake and close at night to conserve water.",
        activity: "Look at stomata under a leaf surface replica.",
        question: "What tiny leaf pores allow CO2 entry?",
        choices: ["Stomata", "Xylem", "Phloem"],
        answer: "Stomata",
      },
      {
        id: 4,
        title: "5. Water Absorption by Roots",
        intro: "Water is drawn up from soil by root hair cells and transported to leaves.",
        explanation: "Root hairs increase surface area for water absorption via osmosis.",
        example: "Water travels up through xylem vessels to reach leaf cells.",
        activity: "Place celery in food-colored water to observe capillary transport.",
        question: "Which tissue carries water up from roots to leaves?",
        choices: ["Xylem", "Phloem", "Epidermis"],
        answer: "Xylem",
      },
      {
        id: 5,
        title: "6. Chlorophyll & Light Absorption",
        intro: "Chlorophyll reflects green light and absorbs blue and red wavelengths.",
        explanation: "Because green light is reflected rather than absorbed, plants appear green to human eyes.",
        example: "Autumn leaves change color when chlorophyll breaks down to reveal carotenoid pigments.",
        activity: "Separate leaf pigments using paper chromatography.",
        question: "Why do most plant leaves appear green?",
        choices: ["Chlorophyll reflects green light", "Chlorophyll absorbs green light", "Stomata emit green glow"],
        answer: "Chlorophyll reflects green light",
      },
      {
        id: 6,
        title: "7. Chemical Reaction of Photosynthesis",
        intro: "The balanced chemical equation represents reactants converting into products.",
        explanation: "6CO₂ + 6H₂O + Light Energy → C₆H₁₂O₆ + 6O₂.",
        example: "6 carbon dioxide molecules + 6 water molecules yield 1 glucose + 6 oxygen molecules.",
        activity: "Balance the chemical equation for photosynthesis.",
        question: "What are the primary reactants in photosynthesis?",
        choices: ["CO₂ and H₂O", "Glucose and O₂", "Nitrogen and Oxygen"],
        answer: "CO₂ and H₂O",
      },
      {
        id: 7,
        title: "8. Glucose Production & Energy Storage",
        intro: "Glucose is a sugar that plants use for immediate energy or store as starch.",
        explanation: "Plants link glucose molecules together into starch for long-term energy reserves in roots and seeds.",
        example: "Potatoes store surplus photosynthetic energy as starch underground.",
        activity: "Test a green leaf for starch using iodine solution.",
        question: "In what form do plants store surplus glucose?",
        choices: ["Starch", "Protein", "Fat"],
        answer: "Starch",
      },
      {
        id: 8,
        title: "9. Oxygen Release",
        intro: "Oxygen is produced as a byproduct of splitting water molecules.",
        explanation: "Oxygen gas diffuses out of leaf stomata into the atmosphere, supplying air for breathing animals.",
        example: "Aquatic plants like Elodea produce visible oxygen bubbles underwater in sunlight.",
        activity: "Count oxygen bubbles produced by Elodea under different light distances.",
        question: "What gas is released into the air as a byproduct of photosynthesis?",
        choices: ["Oxygen", "Carbon dioxide", "Hydrogen"],
        answer: "Oxygen",
      },
      {
        id: 9,
        title: "10. Factors Affecting Photosynthesis Rate",
        intro: "Light intensity, CO₂ concentration, and temperature dictate photosynthetic speed.",
        explanation: "If any factor is insufficient, it acts as a limiting factor that caps the rate of photosynthesis.",
        example: "Increasing light intensity speeds up photosynthesis until a maximum saturation point is reached.",
        activity: "Graph photosynthesis rate against light intensity.",
        question: "Which of the following can limit the rate of photosynthesis?",
        choices: ["Low CO₂ concentration", "High glucose levels", "Excess oxygen"],
        answer: "Low CO₂ concentration",
      },
      {
        id: 10,
        title: "11. Ecosystem Importance & Plant Life",
        intro: "Photosynthesis forms the base of food chains and regulates atmospheric oxygen/CO₂ balance.",
        explanation: "Plants are primary producers; without them, aerobic animal life could not exist on Earth.",
        example: "Rainforests are often called the 'lungs of the Earth' due to massive oxygen production.",
        activity: "Create a simple food web diagram showing solar energy flowing from plants to consumers.",
        question: "Why are plants called primary producers in an ecosystem?",
        choices: ["They generate their own food from sunlight", "They consume other organisms", "They break down dead matter"],
        answer: "They generate their own food from sunlight",
      },
    ],
  },

  "States of matter": {
    subject: "Science",
    level: "Grade 6",
    eyebrow: "Particles in motion",
    lessons: [
      {
        id: 0,
        title: "1. Introduction to Matter & Atoms",
        intro: "Matter is anything that has mass and takes up space.",
        explanation: "All matter is made of tiny particles (atoms and molecules) that are constantly in motion.",
        example: "Water, air, wood, and stars are all forms of matter.",
        activity: "List 5 items in your room and identify whether they have mass and volume.",
        question: "What is matter composed of?",
        choices: ["Tiny particles (atoms/molecules)", "Pure light rays", "Empty vacuum"],
        answer: "Tiny particles (atoms/molecules)",
      },
      {
        id: 1,
        title: "2. Properties of Solids",
        intro: "Solids have a definite shape and a definite volume.",
        explanation: "Particles in a solid are packed tightly together in fixed positions and vibrate in place.",
        example: "An ice cube retains its shape whether placed in a glass or on a plate.",
        activity: "Try compressing a wooden block to observe solid rigidity.",
        question: "How are particles arranged in a solid?",
        choices: ["Tightly packed in fixed positions", "Flowing past one another", "Far apart moving rapidly"],
        answer: "Tightly packed in fixed positions",
      },
      {
        id: 2,
        title: "3. Properties of Liquids",
        intro: "Liquids have a definite volume but take the shape of their container.",
        explanation: "Particles in a liquid are close together but can slide past one another freely.",
        example: "100 ml of water has the same volume whether poured into a tall cylinder or wide bowl.",
        activity: "Pour water into different shaped containers to observe shape adaptation.",
        question: "Which property describes a liquid?",
        choices: ["Definite volume, variable shape", "Definite shape, variable volume", "Variable volume and shape"],
        answer: "Definite volume, variable shape",
      },
      {
        id: 3,
        title: "4. Properties of Gases",
        intro: "Gases have neither a definite shape nor a definite volume.",
        explanation: "Gas particles have high kinetic energy, are spaced far apart, and expand to fill any container.",
        example: "Helium fills a balloon completely and compresses easily.",
        activity: "Trap air in a syringe and compress it to demonstrate gas compressibility.",
        question: "Which state of matter fills its container completely and compresses easily?",
        choices: ["Gas", "Liquid", "Solid"],
        answer: "Gas",
      },
      {
        id: 4,
        title: "5. Particle Theory of Matter",
        intro: "Matter can be solid, liquid, or gas depending on particle arrangement and thermal energy.",
        explanation: "Heating gives particles more kinetic energy, causing them to move faster and further apart.",
        example: "ice → water → steam",
        activity: "Compare particle spacing in ice, liquid water, and steam.",
        question: "Which state has particles moving most freely?",
        choices: ["Gas", "Liquid", "Solid"],
        answer: "Gas",
      },
      {
        id: 5,
        title: "6. Melting & Freezing",
        intro: "Melting changes solid to liquid; freezing changes liquid to solid.",
        explanation: "Adding heat energy melts solids at their melting point. Removing heat energy freezes liquids.",
        example: "Water freezes at 0°C and ice melts at 0°C.",
        activity: "Track the temperature of melting ice water over time.",
        question: "What temperature is the freezing point of pure water at sea level?",
        choices: ["0°C", "100°C", "32°C"],
        answer: "0°C",
      },
      {
        id: 6,
        title: "7. Evaporation & Condensation",
        intro: "Evaporation turns liquid into gas; condensation turns gas into liquid.",
        explanation: "Evaporation occurs at liquid surfaces. Condensation happens when gas cools against a cold surface.",
        example: "Water droplets forming on the outside of an iced glass display condensation.",
        activity: "Observe mist condensing on a cold mirror.",
        question: "Water droplets forming on a cold glass display:",
        choices: ["Condensation", "Evaporation", "Sublimation"],
        answer: "Condensation",
      },
      {
        id: 7,
        title: "8. Sublimation & Deposition",
        intro: "Sublimation changes solid directly to gas without becoming liquid.",
        explanation: "Deposition is the reverse process: gas changes directly to solid.",
        example: "Dry ice (solid CO₂) sublimates into gas at room temperature.",
        activity: "Watch frost form directly from water vapor on a frozen can.",
        question: "Dry ice turning directly into gas is an example of:",
        choices: ["Sublimation", "Melting", "Evaporation"],
        answer: "Sublimation",
      },
      {
        id: 8,
        title: "9. Temperature & Kinetic Energy",
        intro: "Temperature measures the average kinetic energy of particles in a substance.",
        explanation: "Higher temperature means faster particle motion and increased kinetic energy.",
        example: "Molecules in boiling water move much faster than in cold water.",
        activity: "Drop food dye in hot vs cold water to compare diffusion rates.",
        question: "What happens to particle movement as temperature increases?",
        choices: ["Particles move faster", "Particles move slower", "Particles stop moving"],
        answer: "Particles move faster",
      },
      {
        id: 9,
        title: "10. Gas Pressure & Volume",
        intro: "Gas particles colliding with container walls create gas pressure.",
        explanation: "Decreasing container volume increases collision frequency and gas pressure (Boyle's Law).",
        example: "Pressing down on a bicycle pump compresses air and increases pressure.",
        activity: "Observe a marshmallow expand in a vacuum chamber.",
        question: "What causes gas pressure inside a container?",
        choices: ["Particles colliding with container walls", "Gravity pulling particles down", "Liquid condensation"],
        answer: "Particles colliding with container walls",
      },
      {
        id: 10,
        title: "11. Phase Changes in Daily Life",
        intro: "Phase changes drive the water cycle, weather patterns, and culinary processes.",
        explanation: "Evaporation, condensation, and precipitation continuously cycle water through Earth's atmosphere.",
        example: "Puddles dry up after rain due to solar evaporation.",
        activity: "Diagram phase changes in the global water cycle.",
        question: "Which process turns surface lake water into atmospheric vapor?",
        choices: ["Evaporation", "Freezing", "Deposition"],
        answer: "Evaporation",
      },
    ],
  },

  "Parts of a plant": {
    subject: "Science",
    level: "Grade 5",
    eyebrow: "Roots, stems, and leaves",
    lessons: [
      {
        id: 0,
        title: "1. Plant Structure Overview",
        intro: "Each plant part has a specific role that helps the plant grow, reproduce, and survive.",
        explanation: "Roots absorb water, stems support and transport materials, leaves make food, and flowers reproduce.",
        example: "Roots → water | Stem → transport | Leaves → food",
        activity: "Match each plant part to its job, then explain how the parts work together.",
        question: "Which plant part absorbs water from the soil?",
        choices: ["Roots", "Leaves", "Flowers"],
        answer: "Roots",
      },
      {
        id: 1,
        title: "2. Roots: Water & Nutrient Absorption",
        intro: "Roots anchor the plant in soil and absorb minerals and water.",
        explanation: "Taproots reach deep into the ground (like carrots), while fibrous roots spread wide.",
        example: "A carrot is a thick taproot storing plant nutrients.",
        activity: "Compare a carrot (taproot) with grass roots (fibrous roots).",
        question: "What is the primary job of plant roots?",
        choices: ["Absorb water and minerals", "Make seeds", "Capture sunlight"],
        answer: "Absorb water and minerals",
      },
      {
        id: 2,
        title: "3. Stems: Support & Transport System",
        intro: "Stems hold leaves up to sunlight and transport water and food throughout the plant.",
        explanation: "Internal vascular bundles (xylem and phloem) run through stems like elevated highways.",
        example: "Tree trunks are woody stems providing strong structural support.",
        activity: "Examine rings in a cross-section stem slice.",
        question: "What is the main function of a plant stem?",
        choices: ["Support leaves and transport fluids", "Absorb soil nutrients", "Attract pollinators"],
        answer: "Support leaves and transport fluids",
      },
      {
        id: 3,
        title: "4. Leaves: Photosynthesis & Gas Exchange",
        intro: "Leaves act as solar panels that capture sunlight to produce glucose.",
        explanation: "Flat wide blades maximize light absorption while stomatal pores exchange oxygen and CO₂.",
        example: "Broad maple leaves catch sunlight efficiently in forest canopies.",
        activity: "Measure leaf surface area using grid paper.",
        question: "Why are most leaves flat and wide?",
        choices: ["To maximize sunlight absorption", "To store heavy rocks", "To absorb rainwater directly"],
        answer: "To maximize sunlight absorption",
      },
      {
        id: 4,
        title: "5. Flowers: Reproductive Structures",
        intro: "Flowers contain reproductive organs that produce seeds and fruit.",
        explanation: "Petals attract pollinators like bees. Stamens make pollen; pistils contain ovules.",
        example: "Bright yellow sunflower petals signal bees to visit.",
        activity: "Dissect a flower to identify petals, stamen, and pistil.",
        question: "What part of a flower attracts insect pollinators?",
        choices: ["Petals", "Roots", "Sepals"],
        answer: "Petals",
      },
      {
        id: 5,
        title: "6. Seeds & Germination",
        intro: "Seeds protect plant embryos until favorable moisture and temperature trigger growth.",
        explanation: "Germination begins when a seed absorbs water, swells, and sprouts its initial root.",
        example: "Bean seeds sprout roots first, then push shoots upward.",
        activity: "Sprout a bean seed inside a moist paper towel bag.",
        question: "What does a germinating seed sprout first?",
        choices: ["Root", "Flower", "Fruit"],
        answer: "Root",
      },
      {
        id: 6,
        title: "7. Fruit Formation",
        intro: "Fruits develop from fertilized flower ovaries to protect seeds and assist dispersal.",
        explanation: "Animals eat fleshy fruits and scatter seeds in new locations.",
        example: "Apples, tomatoes, and pea pods are all botanically fruits.",
        activity: "Classify culinary vegetables into botanical fruits or roots.",
        question: "What botanical part develops into a fruit after fertilization?",
        choices: ["Ovary", "Stamen", "Leaf"],
        answer: "Ovary",
      },
      {
        id: 7,
        title: "8. Vascular System: Xylem & Phloem",
        intro: "Xylem carries water upward; phloem transports sugars in all directions.",
        explanation: "Xylem is one-way transport from roots up. Phloem carries glucose from leaves to roots and fruits.",
        example: "Maple sap collected in spring flows through phloem/xylem tissue.",
        activity: "Trace nutrient flow arrows on a plant diagram.",
        question: "Which tissue transports sugars made in leaves to other parts of the plant?",
        choices: ["Phloem", "Xylem", "Epidermis"],
        answer: "Phloem",
      },
      {
        id: 8,
        title: "9. Plant Adaptations",
        intro: "Plants adapt their parts to survive extreme environments like deserts or wetlands.",
        explanation: "Cacti have waxy stems and spine leaves to store water and prevent evaporation.",
        example: "Water lilies have floating leaves with air pockets.",
        activity: "Compare cactus spines with rainforest drip-tip leaves.",
        question: "Why do cacti have thick waxy stems and spines?",
        choices: ["To store water and reduce water loss", "To catch snow", "To attract birds"],
        answer: "To store water and reduce water loss",
      },
      {
        id: 9,
        title: "10. How Plants Support Ecosystems",
        intro: "Plants provide oxygen, food, shelter, and soil stabilization for terrestrial ecosystems.",
        explanation: "Plant roots prevent soil erosion, while foliage provides habitats for wildlife.",
        example: "Oak trees support hundreds of insect, bird, and mammal species.",
        activity: "Map animal species that rely on a single oak tree.",
        question: "How do plant roots help prevent land degradation?",
        choices: ["They hold soil in place to prevent erosion", "They block wind", "They produce rain"],
        answer: "They hold soil in place to prevent erosion",
      },
      {
        id: 10,
        title: "11. Plant Care & Growth Cycles",
        intro: "Plants require proper light, water, air, nutrients, and temperature to complete life cycles.",
        explanation: "Annual plants complete life cycles in 1 year; perennials live for many years.",
        example: "Tomatoes are annuals; apple trees are perennials.",
        activity: "Plan a school garden garden patch with annuals and perennials.",
        question: "What term describes a plant that lives and blooms for many years?",
        choices: ["Perennial", "Annual", "Biennial"],
        answer: "Perennial",
      },
    ],
  },
};

// Fallback curriculum generator for any topic not explicitly listed
export function getTopicCurriculum(topicName: string): TopicCurriculum {
  if (TOPIC_CURRICULA[topicName]) {
    return TOPIC_CURRICULA[topicName];
  }

  // Generate a standard 12-lesson curriculum dynamically for any custom topic
  const subject = "General Science";
  const level = "Interactive";
  const eyebrow = `Core concepts of ${topicName}`;

  const defaultTitles = [
    `1. Understanding ${topicName}`,
    `2. Key Principles of ${topicName}`,
    `3. Core Mechanisms`,
    `4. Foundational Models`,
    `5. Analyzing Components`,
    `6. Step-by-Step Operations`,
    `7. Intermediate Applications`,
    `8. Problem Solving Strategies`,
    `9. Advanced Scenarios`,
    `10. Real-World Case Studies`,
    `11. Practical Exercises`,
    `12. Mastery & Review`,
  ];

  const lessons: DetailedLesson[] = defaultTitles.map((title, idx) => ({
    id: idx,
    title,
    intro: `Master the essential principles behind ${topicName} in lesson ${idx + 1}.`,
    explanation: `This lesson covers fundamental concepts, step-by-step reasoning, and practical examples for ${topicName}.`,
    example: `Worked Example ${idx + 1}: Applying key rules of ${topicName}.`,
    activity: `Practice applying lesson ${idx + 1} concepts through live interactive models and checks.`,
    question: `Which statement best describes the key concept in ${title}?`,
    choices: [
      `Option A: Core concept of ${topicName}`,
      `Option B: Secondary property`,
      `Option C: Alternative model`,
    ],
    answer: `Option A: Core concept of ${topicName}`,
  }));

  return { subject, level, eyebrow, lessons };
}

/**
 * UNLOCK LOGIC RULE:
 * - lessonIndex 0, 1, 2 -> Always unlocked (first 3 lessons)
 * - lessonIndex >= 3 -> Unlocked ONLY IF lessonIndex - 1 is completed
 */
export function isLessonUnlocked(lessonIndex: number, completedIndices: number[]): boolean {
  if (lessonIndex < 3) return true;
  return completedIndices.includes(lessonIndex - 1);
}

const STORAGE_PREFIX = "neura-topic-completed-v2-";

export function getTopicCompletedLessons(topic: string): number[] {
  if (typeof window === "undefined") return [];
  try {
    const saved = localStorage.getItem(`${STORAGE_PREFIX}${topic}`);
    if (saved) {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed)) return parsed.map((n) => Number(n));
    }
  } catch (err) {
    console.warn("Failed to read completed lessons from localStorage", err);
  }
  return [];
}

export function setTopicLessonCompleted(topic: string, lessonIndex: number): number[] {
  const current = getTopicCompletedLessons(topic);
  if (!current.includes(lessonIndex)) {
    const updated = [...current, lessonIndex].sort((a, b) => a - b);
    try {
      localStorage.setItem(`${STORAGE_PREFIX}${topic}`, JSON.stringify(updated));
    } catch (err) {
      console.warn("Failed to save completed lesson to localStorage", err);
    }
    if (typeof window !== "undefined") {
      window.dispatchEvent(
        new CustomEvent("neura-lesson-completed", {
          detail: { topic, lessonIndex, completed: updated },
        })
      );
    }
    return updated;
  }
  return current;
}

// Backward compatible export for server/topic-lessons.test.ts
export const lessons = Object.fromEntries(
  Object.entries(TOPIC_CURRICULA).map(([topic, curr]) => [
    topic,
    {
      subject: curr.subject,
      level: curr.level,
      eyebrow: curr.eyebrow,
      intro: curr.lessons[0].intro,
      explanation: curr.lessons[0].explanation,
      example: curr.lessons[0].example,
      activity: curr.lessons[0].activity,
      question: curr.lessons[0].question,
      choices: curr.lessons[0].choices,
      answer: curr.lessons[0].answer,
    },
  ])
);
