from pathlib import Path
p=Path('/home/ubuntu/neura-student-dashboard/client/src/pages/TopicLesson.tsx')
s=p.read_text()
s=s.replace('import { ArrowLeft, CheckCircle2, Clock3, GraduationCap, Leaf, Play, RotateCcw } from "lucide-react";', 'import { ArrowLeft, CheckCircle2, Clock3, Eye, GraduationCap, HelpCircle, Leaf, Lightbulb, Play, RotateCcw, Sparkles } from "lucide-react";')
s=s.replace('  const [completed, setCompleted] = useState(false);', '''  const [completed, setCompleted] = useState(false);
  const [activeMode, setActiveMode] = useState<"steps" | "visual" | "example" | "simple" | "hint" | "stuck" | null>(null);''')
needle='''  const completeLesson = () => {
    if (completed) return;
    setCompleted(true);
    if (course) {
      logStudy.mutate({ courseId: course.id, minutes: 15 }, { onSuccess: () => void utils.dashboard.overview.invalidate() });
    }
  };'''
replacement=needle+'''\n  const modeContent = activeMode === "steps" ? <ol className="list-decimal space-y-2 pl-5"><li>Start with the key idea: {lesson.intro}</li><li>Focus on the important relationship in {topic}.</li><li>Use the worked example: {lesson.example}.</li><li>Try the quick check and explain your reasoning.</li></ol> : activeMode === "visual" ? <div><p>Follow the concept flow from the starting idea to the result:</p><div className="mt-3 flex flex-wrap items-center gap-2 text-xs font-bold text-[#159ac1]"><span className="rounded-lg bg-white px-3 py-2">Starting idea</span><span>→</span><span className="rounded-lg bg-white px-3 py-2">Key relationship</span><span>→</span><span className="rounded-lg bg-white px-3 py-2">{lesson.example}</span></div></div> : activeMode === "example" ? <div><p>Here is a worked example for {topic}:</p><p className="mt-3 rounded-xl bg-white p-4 text-lg font-bold text-[#1d596b]">{lesson.example}</p><p className="mt-3">{lesson.activity}</p></div> : activeMode === "simple" ? <p>{lesson.explanation.split(".")[0]}.</p> : activeMode === "hint" ? <p><strong>Hint:</strong> Look at the key relationship in the worked example, then apply the same idea to the question.</p> : activeMode === "stuck" ? <div><p>It is completely okay to feel stuck. Take one small step:</p><ul className="mt-2 list-disc space-y-1 pl-5"><li>Read the short explanation again.</li><li>Look at the worked example.</li><li>Try the easiest part of the question first.</li></ul></div> : null;'''
if needle not in s: raise SystemExit('completion function not found')
s=s.replace(needle,replacement,1)
old='''<div className="mt-6 rounded-2xl bg-[#e8f8fc] p-5"><div className="flex items-center gap-2 text-sm font-bold text-[#159ac1]"><Leaf className="h-4 w-4" /> Worked example</div>'''
new='''<div className="mt-6"><p className="mb-3 text-sm font-bold text-[#315866]">Choose how you would like to learn</p><div className="flex flex-wrap gap-2"><button onClick={() => setActiveMode("steps")} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${activeMode === "steps" ? "bg-[#159ac1] text-white" : "bg-[#e8f8fc] text-[#159ac1] hover:bg-[#d7f2f7]"}`}><Sparkles className="mr-1 inline h-3.5 w-3.5" /> Step by step</button><button onClick={() => setActiveMode("visual")} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${activeMode === "visual" ? "bg-[#159ac1] text-white" : "bg-[#e8f8fc] text-[#159ac1] hover:bg-[#d7f2f7]"}`}><Eye className="mr-1 inline h-3.5 w-3.5" /> Show visually</button><button onClick={() => setActiveMode("example")} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${activeMode === "example" ? "bg-[#159ac1] text-white" : "bg-[#e8f8fc] text-[#159ac1] hover:bg-[#d7f2f7]"}`}><Lightbulb className="mr-1 inline h-3.5 w-3.5" /> Show an example</button><button onClick={() => setActiveMode("simple")} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${activeMode === "simple" ? "bg-[#159ac1] text-white" : "bg-[#e8f8fc] text-[#159ac1] hover:bg-[#d7f2f7]"}`}><BookOpenIcon /> Explain simply</button><button onClick={() => setActiveMode("hint")} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${activeMode === "hint" ? "bg-[#159ac1] text-white" : "bg-[#f0edff] text-[#8979d5] hover:bg-[#e7e2f7]"}`}><HelpCircle className="mr-1 inline h-3.5 w-3.5" /> Give me a hint</button><button onClick={() => setActiveMode("stuck")} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${activeMode === "stuck" ? "bg-[#ef946e] text-white" : "bg-[#fff1e9] text-[#bd6d39] hover:bg-[#ffe4d7]"}`}><HelpCircle className="mr-1 inline h-3.5 w-3.5" /> I’m stuck</button></div>{activeMode && <div className="mt-4 rounded-2xl border border-[#dff0f4] bg-[#fbfeff] p-5 text-sm leading-6 text-[#5e7d87]" aria-live="polite"><div className="mb-2 flex items-center justify-between"><span className="font-bold text-[#315866]">{activeMode === "steps" ? "Step-by-step explanation" : activeMode === "visual" ? "Visual explanation" : activeMode === "example" ? "Example learning" : activeMode === "simple" ? "Simpler explanation" : activeMode === "hint" ? "A gentle hint" : "You are not alone"}</span><button onClick={() => setActiveMode(null)} className="text-xs font-semibold text-[#159ac1]">Close</button></div>{modeContent}</div>}</div><div className="mt-6 rounded-2xl bg-[#e8f8fc] p-5"><div className="flex items-center gap-2 text-sm font-bold text-[#159ac1]"><Leaf className="h-4 w-4" /> Worked example</div>'''
if old not in s: raise SystemExit('worked example insertion point not found')
s=s.replace(old,new,1)
s=s.replace('function TopicLesson()', 'function TopicLesson()', 1)
# Replace helper token with a compact icon component after the page function.
s=s.replace('\nexport { lessons };\n', '\nfunction BookOpenIcon() { return <BookOpenFallback />; }\nfunction BookOpenFallback() { return <span className="mr-1 inline-block text-[13px]">▣</span>; }\n\nexport { lessons };\n')
p.write_text(s)
