from pathlib import Path
p=Path('/home/ubuntu/neura-student-dashboard/client/src/pages/TopicLesson.tsx')
s=p.read_text()
s=s.replace('  const logStudy = trpc.dashboard.logStudy.useMutation();', '  const logStudy = trpc.dashboard.logStudy.useMutation();\n  const recordLearningMode = trpc.dashboard.recordLearningMode.useMutation();')
old='''  const modeContent = activeMode === "steps" ? <ol className="list-decimal space-y-2 pl-5"><li>Start with the key idea: {lesson.intro}</li><li>Focus on the important relationship in {topic}.</li><li>Use the worked example: {lesson.example}.</li><li>Try the quick check and explain your reasoning.</li></ol> : activeMode === "visual" ? <div><p>Follow the concept flow from the starting idea to the result:</p><div className="mt-3 flex flex-wrap items-center gap-2 text-xs font-bold text-[#159ac1]"><span className="rounded-lg bg-white px-3 py-2">Starting idea</span><span>→</span><span className="rounded-lg bg-white px-3 py-2">Key relationship</span><span>→</span><span className="rounded-lg bg-white px-3 py-2">{lesson.example}</span></div></div> : activeMode === "example" ? <div><p>Here is a worked example for {topic}:</p><p className="mt-3 rounded-xl bg-white p-4 text-lg font-bold text-[#1d596b]">{lesson.example}</p><p className="mt-3">{lesson.activity}</p></div> : activeMode === "simple" ? <p>{lesson.explanation.split(".")[0]}.</p> : activeMode === "hint" ? <p><strong>Hint:</strong> Look at the key relationship in the worked example, then apply the same idea to the question.</p> : activeMode === "stuck" ? <div><p>It is completely okay to feel stuck. Take one small step:</p><ul className="mt-2 list-disc space-y-1 pl-5"><li>Read the short explanation again.</li><li>Look at the worked example.</li><li>Try the easiest part of the question first.</li></ul></div> : null;'''
new='''  const selectMode = (mode: NonNullable<typeof activeMode>) => {
    setActiveMode(mode);
    if (course) recordLearningMode.mutate({ courseId: course.id, topic, mode });
  };
  const modeContent = activeMode === "steps" ? <ol className="list-decimal space-y-2 pl-5"><li>Start with the key idea: {lesson.intro}</li><li>Focus on the important relationship in {topic}.</li><li>Use the worked example: {lesson.example}.</li><li>Try the quick check and explain your reasoning.</li></ol> : activeMode === "visual" ? <div><p>Watch the concept flow from the starting idea to the result:</p><VisualDiagram topic={topic} /></div> : activeMode === "example" ? <div><p>Here is a worked example for {topic}:</p><p className="mt-3 rounded-xl bg-white p-4 text-lg font-bold text-[#1d596b]">{lesson.example}</p><p className="mt-3">{lesson.activity}</p></div> : activeMode === "simple" ? <p>{lesson.explanation.split(".")[0]}.</p> : activeMode === "hint" ? <p><strong>Hint:</strong> Look at the key relationship in the worked example, then apply the same idea to the question.</p> : activeMode === "stuck" ? <div><p>It is completely okay to feel stuck. Take one small step:</p><ul className="mt-2 list-disc space-y-1 pl-5"><li>Read the short explanation again.</li><li>Look at the worked example.</li><li>Try the easiest part of the question first.</li></ul></div> : null;'''
if old not in s: raise SystemExit('mode content not found')
s=s.replace(old,new,1)
for mode in ['steps','visual','example','simple','hint','stuck']:
    s=s.replace(f'setActiveMode("{mode}")', f'selectMode("{mode}")')
insert='''
function VisualDiagram({ topic }: { topic: Topic }) {
  if (topic === "Photosynthesis") return <div className="neura-diagram mt-4"><div className="diagram-node sun-node">☀<span>sunlight</span></div><div className="diagram-arrow">→</div><div className="diagram-node leaf-node">🌿<span>leaf</span></div><div className="diagram-arrow">→</div><div className="diagram-node food-node">✦<span>glucose</span></div><div className="diagram-caption">CO₂ enters · O₂ leaves</div></div>;
  if (topic === "States of matter") return <div className="neura-diagram matter-diagram mt-4"><div><b>Solid</b><span className="particle-grid">••<br />••</span></div><div className="diagram-arrow">→</div><div><b>Liquid</b><span className="particle-grid loose">• •<br /> ••</span></div><div className="diagram-arrow">→</div><div><b>Gas</b><span className="particle-grid spread">•　•<br />　•</span></div><div className="diagram-caption">heat adds energy and space</div></div>;
  if (topic === "Parts of a plant") return <div className="neura-diagram plant-diagram mt-4"><div className="plant-root">roots<br /><small>absorb water</small></div><div className="plant-stem">stem<br /><small>transports</small></div><div className="plant-leaf">leaves<br /><small>make food</small></div></div>;
  if (topic === "Geometry") return <div className="neura-diagram mt-4"><svg viewBox="0 0 260 100" className="diagram-svg" aria-label="Triangle angle diagram"><path d="M30 80 L130 15 L230 80 Z" /><text x="38" y="72">60°</text><text x="120" y="31">50°</text><text x="197" y="72">70°</text></svg><div className="diagram-caption">60° + 50° + 70° = 180°</div></div>;
  if (topic === "Linear equations") return <div className="neura-diagram mt-4"><div className="balance-pan">2x + 3</div><div className="balance-beam">=</div><div className="balance-pan">11</div><div className="diagram-caption">remove 3, then divide by 2 → x = 4</div></div>;
  return <div className="neura-diagram mt-4"><div className="fraction-circle"><span>3</span><span>4</span></div><div className="diagram-arrow">=</div><div className="fraction-circle"><span>6</span><span>8</span></div><div className="diagram-caption">multiply numerator and denominator by 2</div></div>;
}
'''
s=s.replace('\nfunction BookOpenIcon()', insert+'\nfunction BookOpenIcon()',1)
p.write_text(s)
